"""Cargo unit graphs generated by refresh.py; cargo 1.99.0-nightly (eb98b54bc 2026-08-11)."""

METADATA = json.decode(r"""
{
  "workspace_root": "/workspace",
  "workspace_default_members": [
    "path+file:///workspace/consumer#1.0.0"
  ],
  "packages": [
    {
      "name": "consumer",
      "version": "1.0.0",
      "id": "path+file:///workspace/consumer#1.0.0",
      "dependencies": [
        {
          "name": "helper",
          "source": null,
          "req": "*",
          "kind": null,
          "rename": null,
          "optional": false,
          "uses_default_features": false,
          "features": [
            "target"
          ],
          "target": null,
          "registry": null,
          "path": "/workspace/helper"
        },
        {
          "name": "derive-package",
          "source": null,
          "req": "*",
          "kind": null,
          "rename": "renamed",
          "optional": false,
          "uses_default_features": true,
          "features": [
            "extra"
          ],
          "target": null,
          "registry": null,
          "path": "/workspace/derive-package"
        },
        {
          "name": "helper",
          "source": null,
          "req": "*",
          "kind": "dev",
          "rename": null,
          "optional": false,
          "uses_default_features": true,
          "features": [
            "dev"
          ],
          "target": null,
          "registry": null,
          "path": "/workspace/helper"
        },
        {
          "name": "dev-macro",
          "source": null,
          "req": "*",
          "kind": "dev",
          "rename": "macro-test",
          "optional": false,
          "uses_default_features": true,
          "features": [],
          "target": null,
          "registry": null,
          "path": "/workspace/dev-macro"
        },
        {
          "name": "builder",
          "source": null,
          "req": "*",
          "kind": "build",
          "rename": null,
          "optional": false,
          "uses_default_features": true,
          "features": [],
          "target": null,
          "registry": null,
          "path": "/workspace/builder"
        },
        {
          "name": "helper",
          "source": null,
          "req": "*",
          "kind": null,
          "rename": null,
          "optional": false,
          "uses_default_features": false,
          "features": [
            "windows"
          ],
          "target": "cfg(windows)",
          "registry": null,
          "path": "/workspace/helper"
        }
      ],
      "targets": [
        {
          "name": "consumer",
          "kind": [
            "lib"
          ]
        },
        {
          "name": "build-script-build",
          "kind": [
            "custom-build"
          ]
        }
      ],
      "features": {},
      "manifest_path": "/workspace/consumer/Cargo.toml"
    },
    {
      "name": "helper",
      "version": "1.0.0",
      "id": "path+file:///workspace/helper#1.0.0",
      "dependencies": [],
      "targets": [
        {
          "name": "helper",
          "kind": [
            "lib"
          ]
        }
      ],
      "features": {
        "builder": [],
        "default": [
          "std"
        ],
        "dev": [],
        "extra": [],
        "macro": [],
        "macro-test": [],
        "std": [],
        "target": [],
        "windows": []
      },
      "manifest_path": "/workspace/helper/Cargo.toml"
    },
    {
      "name": "derive-package",
      "version": "1.0.0",
      "id": "path+file:///workspace/derive-package#1.0.0",
      "dependencies": [
        {
          "name": "helper",
          "source": null,
          "req": "*",
          "kind": null,
          "rename": null,
          "optional": false,
          "uses_default_features": false,
          "features": [
            "macro"
          ],
          "target": null,
          "registry": null,
          "path": "/workspace/helper"
        },
        {
          "name": "dev-only",
          "source": null,
          "req": "*",
          "kind": "dev",
          "rename": null,
          "optional": false,
          "uses_default_features": true,
          "features": [],
          "target": null,
          "registry": null,
          "path": "/workspace/dev-only"
        }
      ],
      "targets": [
        {
          "name": "renamed_macro",
          "kind": [
            "proc-macro"
          ]
        }
      ],
      "features": {
        "extra": [
          "helper/extra"
        ]
      },
      "manifest_path": "/workspace/derive-package/Cargo.toml"
    },
    {
      "name": "dev-only",
      "version": "1.0.0",
      "id": "path+file:///workspace/dev-only#1.0.0",
      "dependencies": [],
      "targets": [
        {
          "name": "dev_only",
          "kind": [
            "lib"
          ]
        }
      ],
      "features": {},
      "manifest_path": "/workspace/dev-only/Cargo.toml"
    },
    {
      "name": "dev-macro",
      "version": "1.0.0",
      "id": "path+file:///workspace/dev-macro#1.0.0",
      "dependencies": [
        {
          "name": "helper",
          "source": null,
          "req": "*",
          "kind": null,
          "rename": null,
          "optional": false,
          "uses_default_features": false,
          "features": [
            "macro-test"
          ],
          "target": null,
          "registry": null,
          "path": "/workspace/helper"
        }
      ],
      "targets": [
        {
          "name": "dev_macro",
          "kind": [
            "proc-macro"
          ]
        }
      ],
      "features": {},
      "manifest_path": "/workspace/dev-macro/Cargo.toml"
    },
    {
      "name": "builder",
      "version": "1.0.0",
      "id": "path+file:///workspace/builder#1.0.0",
      "dependencies": [
        {
          "name": "helper",
          "source": null,
          "req": "*",
          "kind": null,
          "rename": null,
          "optional": false,
          "uses_default_features": false,
          "features": [
            "builder"
          ],
          "target": null,
          "registry": null,
          "path": "/workspace/helper"
        },
        {
          "name": "helper",
          "source": null,
          "req": "*",
          "kind": "dev",
          "rename": null,
          "optional": false,
          "uses_default_features": true,
          "features": [
            "dev"
          ],
          "target": null,
          "registry": null,
          "path": "/workspace/helper"
        }
      ],
      "targets": [
        {
          "name": "builder",
          "kind": [
            "lib"
          ]
        }
      ],
      "features": {},
      "manifest_path": "/workspace/builder/Cargo.toml"
    },
    {
      "name": "unused",
      "version": "1.0.0",
      "id": "path+file:///workspace/unused#1.0.0",
      "dependencies": [
        {
          "name": "helper",
          "source": null,
          "req": "*",
          "kind": null,
          "rename": null,
          "optional": false,
          "uses_default_features": true,
          "features": [
            "dev"
          ],
          "target": null,
          "registry": null,
          "path": "/workspace/helper"
        }
      ],
      "targets": [
        {
          "name": "unused",
          "kind": [
            "lib"
          ]
        }
      ],
      "features": {},
      "manifest_path": "/workspace/unused/Cargo.toml"
    }
  ]
}
""")

CASES = json.decode(r"""
[
  {
    "package": "consumer",
    "target": "aarch64-apple-darwin",
    "include_dev": false,
    "units": [
      {
        "id": "path+file:///workspace/builder#1.0.0",
        "name": "builder",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": null,
        "features": []
      },
      {
        "id": "path+file:///workspace/consumer#1.0.0",
        "name": "consumer",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": "aarch64-apple-darwin",
        "features": []
      },
      {
        "id": "path+file:///workspace/derive-package#1.0.0",
        "name": "renamed_macro",
        "kind": [
          "proc-macro"
        ],
        "mode": "build",
        "platform": null,
        "features": [
          "extra"
        ]
      },
      {
        "id": "path+file:///workspace/helper#1.0.0",
        "name": "helper",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": null,
        "features": [
          "builder",
          "extra",
          "macro"
        ]
      },
      {
        "id": "path+file:///workspace/helper#1.0.0",
        "name": "helper",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": "aarch64-apple-darwin",
        "features": [
          "target"
        ]
      }
    ]
  },
  {
    "package": "consumer",
    "target": "aarch64-apple-darwin",
    "include_dev": true,
    "units": [
      {
        "id": "path+file:///workspace/builder#1.0.0",
        "name": "builder",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": null,
        "features": []
      },
      {
        "id": "path+file:///workspace/consumer#1.0.0",
        "name": "consumer",
        "kind": [
          "lib"
        ],
        "mode": "test",
        "platform": "aarch64-apple-darwin",
        "features": []
      },
      {
        "id": "path+file:///workspace/consumer#1.0.0",
        "name": "consumer",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": "aarch64-apple-darwin",
        "features": []
      },
      {
        "id": "path+file:///workspace/consumer#1.0.0",
        "name": "consumer",
        "kind": [
          "lib"
        ],
        "mode": "doctest",
        "platform": "aarch64-apple-darwin",
        "features": []
      },
      {
        "id": "path+file:///workspace/derive-package#1.0.0",
        "name": "renamed_macro",
        "kind": [
          "proc-macro"
        ],
        "mode": "build",
        "platform": null,
        "features": [
          "extra"
        ]
      },
      {
        "id": "path+file:///workspace/dev-macro#1.0.0",
        "name": "dev_macro",
        "kind": [
          "proc-macro"
        ],
        "mode": "build",
        "platform": null,
        "features": []
      },
      {
        "id": "path+file:///workspace/helper#1.0.0",
        "name": "helper",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": null,
        "features": [
          "builder",
          "extra",
          "macro",
          "macro-test"
        ]
      },
      {
        "id": "path+file:///workspace/helper#1.0.0",
        "name": "helper",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": "aarch64-apple-darwin",
        "features": [
          "default",
          "dev",
          "std",
          "target"
        ]
      }
    ]
  },
  {
    "package": "consumer",
    "target": "x86_64-pc-windows-msvc",
    "include_dev": false,
    "units": [
      {
        "id": "path+file:///workspace/builder#1.0.0",
        "name": "builder",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": null,
        "features": []
      },
      {
        "id": "path+file:///workspace/consumer#1.0.0",
        "name": "consumer",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": "x86_64-pc-windows-msvc",
        "features": []
      },
      {
        "id": "path+file:///workspace/derive-package#1.0.0",
        "name": "renamed_macro",
        "kind": [
          "proc-macro"
        ],
        "mode": "build",
        "platform": null,
        "features": [
          "extra"
        ]
      },
      {
        "id": "path+file:///workspace/helper#1.0.0",
        "name": "helper",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": "x86_64-pc-windows-msvc",
        "features": [
          "target",
          "windows"
        ]
      },
      {
        "id": "path+file:///workspace/helper#1.0.0",
        "name": "helper",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": null,
        "features": [
          "builder",
          "extra",
          "macro"
        ]
      }
    ]
  },
  {
    "package": "consumer",
    "target": "x86_64-pc-windows-msvc",
    "include_dev": true,
    "units": [
      {
        "id": "path+file:///workspace/builder#1.0.0",
        "name": "builder",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": null,
        "features": []
      },
      {
        "id": "path+file:///workspace/consumer#1.0.0",
        "name": "consumer",
        "kind": [
          "lib"
        ],
        "mode": "test",
        "platform": "x86_64-pc-windows-msvc",
        "features": []
      },
      {
        "id": "path+file:///workspace/consumer#1.0.0",
        "name": "consumer",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": "x86_64-pc-windows-msvc",
        "features": []
      },
      {
        "id": "path+file:///workspace/consumer#1.0.0",
        "name": "consumer",
        "kind": [
          "lib"
        ],
        "mode": "doctest",
        "platform": "x86_64-pc-windows-msvc",
        "features": []
      },
      {
        "id": "path+file:///workspace/derive-package#1.0.0",
        "name": "renamed_macro",
        "kind": [
          "proc-macro"
        ],
        "mode": "build",
        "platform": null,
        "features": [
          "extra"
        ]
      },
      {
        "id": "path+file:///workspace/dev-macro#1.0.0",
        "name": "dev_macro",
        "kind": [
          "proc-macro"
        ],
        "mode": "build",
        "platform": null,
        "features": []
      },
      {
        "id": "path+file:///workspace/helper#1.0.0",
        "name": "helper",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": "x86_64-pc-windows-msvc",
        "features": [
          "default",
          "dev",
          "std",
          "target",
          "windows"
        ]
      },
      {
        "id": "path+file:///workspace/helper#1.0.0",
        "name": "helper",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": null,
        "features": [
          "builder",
          "extra",
          "macro",
          "macro-test"
        ]
      }
    ]
  },
  {
    "package": "derive-package",
    "target": "aarch64-apple-darwin",
    "include_dev": false,
    "units": [
      {
        "id": "path+file:///workspace/derive-package#1.0.0",
        "name": "renamed_macro",
        "kind": [
          "proc-macro"
        ],
        "mode": "build",
        "platform": null,
        "features": []
      },
      {
        "id": "path+file:///workspace/helper#1.0.0",
        "name": "helper",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": null,
        "features": [
          "macro"
        ]
      }
    ]
  },
  {
    "package": "derive-package",
    "target": "aarch64-apple-darwin",
    "include_dev": true,
    "units": [
      {
        "id": "path+file:///workspace/derive-package#1.0.0",
        "name": "renamed_macro",
        "kind": [
          "proc-macro"
        ],
        "mode": "test",
        "platform": null,
        "features": []
      },
      {
        "id": "path+file:///workspace/derive-package#1.0.0",
        "name": "renamed_macro",
        "kind": [
          "proc-macro"
        ],
        "mode": "build",
        "platform": null,
        "features": []
      },
      {
        "id": "path+file:///workspace/derive-package#1.0.0",
        "name": "renamed_macro",
        "kind": [
          "proc-macro"
        ],
        "mode": "doctest",
        "platform": null,
        "features": []
      },
      {
        "id": "path+file:///workspace/dev-only#1.0.0",
        "name": "dev_only",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": null,
        "features": []
      },
      {
        "id": "path+file:///workspace/helper#1.0.0",
        "name": "helper",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": null,
        "features": [
          "macro"
        ]
      }
    ]
  },
  {
    "package": "derive-package",
    "target": "x86_64-pc-windows-msvc",
    "include_dev": false,
    "units": [
      {
        "id": "path+file:///workspace/derive-package#1.0.0",
        "name": "renamed_macro",
        "kind": [
          "proc-macro"
        ],
        "mode": "build",
        "platform": null,
        "features": []
      },
      {
        "id": "path+file:///workspace/helper#1.0.0",
        "name": "helper",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": null,
        "features": [
          "macro"
        ]
      }
    ]
  },
  {
    "package": "derive-package",
    "target": "x86_64-pc-windows-msvc",
    "include_dev": true,
    "units": [
      {
        "id": "path+file:///workspace/derive-package#1.0.0",
        "name": "renamed_macro",
        "kind": [
          "proc-macro"
        ],
        "mode": "test",
        "platform": null,
        "features": []
      },
      {
        "id": "path+file:///workspace/derive-package#1.0.0",
        "name": "renamed_macro",
        "kind": [
          "proc-macro"
        ],
        "mode": "doctest",
        "platform": null,
        "features": []
      },
      {
        "id": "path+file:///workspace/derive-package#1.0.0",
        "name": "renamed_macro",
        "kind": [
          "proc-macro"
        ],
        "mode": "build",
        "platform": null,
        "features": []
      },
      {
        "id": "path+file:///workspace/dev-only#1.0.0",
        "name": "dev_only",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": null,
        "features": []
      },
      {
        "id": "path+file:///workspace/helper#1.0.0",
        "name": "helper",
        "kind": [
          "lib"
        ],
        "mode": "build",
        "platform": null,
        "features": [
          "macro"
        ]
      }
    ]
  }
]
""")
