"""Refresh the Cargo oracle with a nightly toolchain; writes no compiled artifacts.

Run: CARGO=/path/to/nightly/bin/cargo RUSTC=/path/to/nightly/bin/rustc \
    python3 rs/private/feature_context_fixture/refresh.py
"""

import json
import os
from pathlib import Path
import subprocess

root = Path(__file__).resolve().parent
cargo = os.environ.get("CARGO", "cargo")

def run(*args):
    return json.loads(subprocess.check_output([cargo, *args], cwd=root, text=True))

metadata = run("metadata", "--no-deps", "--offline", "--format-version=1")
workspace = metadata["workspace_root"]
# Normalize paths, including package IDs, so fixtures can be regenerated anywhere.
metadata = json.loads(json.dumps(metadata).replace(workspace, "/workspace"))
metadata = {key: metadata[key] for key in ["workspace_root", "workspace_default_members", "packages"]}
for package in metadata["packages"]:
    for key in list(package):
        if key not in ["id", "name", "version", "manifest_path", "features", "dependencies", "targets"]:
            del package[key]
    package["targets"] = [{"name": t["name"], "kind": t["kind"]} for t in package["targets"]]
cases = []
for package in ["consumer", "derive-package"]:
    for target in ["aarch64-apple-darwin", "x86_64-pc-windows-msvc"]:
        for include_dev in [False, True]:
            graph = run("test" if include_dev else "build", "--offline", "--unit-graph", "-Z", "unstable-options", "--target", target, "-p", package)
            units = []
            for unit in graph["units"]:
                if "custom-build" in unit["target"]["kind"]:
                    continue
                units.append({
                    "id": unit["pkg_id"].replace(workspace, "/workspace"),
                    "name": unit["target"]["name"],
                    "kind": unit["target"]["kind"],
                    "mode": unit["mode"],
                    "platform": unit["platform"],
                    "features": unit["features"],
                })
            cases.append({"package": package, "target": target, "include_dev": include_dev, "units": units})
version = subprocess.check_output([cargo, "--version"], text=True).strip()
content = '"""Cargo unit graphs generated by refresh.py; ' + version + '."""\n'
for name, data in [("METADATA", metadata), ("CASES", cases)]:
    content += '\n' + name + ' = json.decode(r"""\n' + json.dumps(data, indent=2) + '\n""")\n'
(root / "oracle.bzl").write_text(content)
