load("@bazel_lib//:bzl_library.bzl", "bzl_library")
load(":tests.bzl", "visibility_denied_tests")

visibility_denied_tests()

filegroup(
    name = "metadata",
    srcs = [
        "@visibility_lib//:sample_package_metadata",
        "@visibility_macro//:sample_package_metadata",
    ],
)

bzl_library(
    name = "repos",
    srcs = ["repos.bzl"],
    deps = [
        "//rs/private:repository_utils",
        "//rs/private:visibility",
    ],
)

bzl_library(
    name = "tests",
    srcs = ["tests.bzl"],
    deps = ["@bazel_skylib//lib:unittest"],
)
